/**
Diagram depicting situation where a user creates a new note on https://studies.cs.helsinki.fi/exampleapp/notes by using a form field.
*/

sequenceDiagram
    participant browser
    participant server

    browser->>server: Button clicked, POST https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server
    server-->>browser: HTML document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: CSS file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: JavaScript file
    deactivate server

    Note right of browser: Browser executes JavaScript code which fetches JSON from server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: [{ "content": "New Note", "date": "2023-06-19" }, ... ]
    deactivate server

    Note right of browser: Browser executes callback function to render all notes
